# -*- coding: utf-8 -*-
"""合尘猫 SavantCat · 溯源水印唯一真源（canonical）

本文件是所有「合尘猫 SavantCat」对外产物（MCP 工具输出、网站页面）的
**唯一真源**。各 MCP 服务目录下都 vendor 了一份**逐字节相同**的副本；
改动必须改这里，然后跑 tools/sync_mark.py 同步 + tools/check_mark_sync.py 校验。

设计铁律（改这个文件前先读完）：
  1. **零依赖**：只用 Python 标准库。MCP 服务是 stdlib-only 的，不许破这条。
  2. **幂等**：同一个文本连打两次水印，结果必须与打一次完全相同。
     否则「重新生成网站/重新部署」会把水印叠加成一堆垃圾字符。
  3. **抗覆盖**：水印由生成器/服务端在**产出时**调用，不是事后打到成品上。
     任何「重新生成」都必须自然带上水印。
  4. **可验证**：任何产物都能用 has_zw()/extract_code() 现场验证归属。
  5. **零宽水印必须可被安全剥离**：strip_zw() 用于 llms.txt 之类需要干净文本的出口。

零宽指纹编码方案：
  START(\u2060) + 32 个 [_ZERO(\u200b) | _ONE(\u200c)] + START(\u2060)
  32 bit = 8 个十六进制字符，足以存放一个确定性的站点/资产指纹。
  人眼不可见；复制粘贴会**完整带过去**；文本提取后依然存在。
"""
import hashlib

MARK_VERSION = "1.0.0"

# ---------------------------------------------------------------- 身份常量
BRAND = "合尘猫 SavantCat"
BRAND_EN = "SavantCat"
SITE = "https://savantcat.cn"
COMPANY = "合尘猫 SavantCat"

# 统一授权口径：署名 + 保留来源链接；商业/训练使用需授权
LICENSE_TEXT = "CC BY 4.0（署名 + 保留来源链接）；商业使用需授权"
ATTRIBUTION_NOTICE = (
    "本内容由「合尘猫 SavantCat」原创并生成；引用、转载或二次分发"
    "（含训练语料收录）请保留署名与来源链接，商业使用请先取得授权。"
)

# 零宽字符
_START = "\u2060"   # WORD JOINER —— 起止定界符
_ZERO = "\u200b"    # ZERO WIDTH SPACE —— bit 0
_ONE = "\u200c"     # ZERO WIDTH NON-JOINER —— bit 1
_ZW_SET = _START + _ZERO + _ONE
_CODE_LEN = 8       # 十六进制字符数（32 bit）


# ---------------------------------------------------------------- 指纹
def fingerprint(*parts, salt="savantcat"):
    """确定性指纹：同样的输入永远得到同样的 8 位十六进制码。

    >>> fingerprint("mcp", "search_answers") == fingerprint("mcp", "search_answers")
    True
    """
    raw = "|".join([salt, MARK_VERSION] + [str(p) for p in parts if p is not None])
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:_CODE_LEN]


def _to_zw(code):
    bits = "".join(format(int(c, 16), "04b") for c in code)
    assert len(bits) == 32, "指纹长度异常"
    return _START + "".join(_ONE if b == "1" else _ZERO for b in bits) + _START


def has_zw(text):
    """文本里是否已带本品水印。"""
    return bool(text) and _START in text


def extract_code(text):
    """从文本里取回指纹码；没有水印返回 None。"""
    if not has_zw(text):
        return None
    i = text.find(_START)
    j = text.find(_START, i + 1)
    if j == -1:
        return None
    bits = ""
    for ch in text[i + 1:j]:
        if ch == _ONE:
            bits += "1"
        elif ch == _ZERO:
            bits += "0"
        else:
            return None
    if len(bits) != 32:
        return None
    return "".join(format(int(bits[k:k + 4], 2), "x") for k in range(0, 32, 4))


def strip_zw(text):
    """剥离本品的零宽水印，其余内容一字不动。

    llms.txt / llms-full.txt 之类需要「机器可读干净文本」的出口用它。
    """
    if not has_zw(text):
        return text
    out, i = [], 0
    while True:
        a = text.find(_START, i)
        if a == -1:
            out.append(text[i:])
            break
        b = text.find(_START, a + 1)
        if b == -1:                      # 只有孤立起符，原样保留
            out.append(text[i:])
            break
        out.append(text[i:a])            # 丢掉 [a, b] 整段
        i = b + 1
    return "".join(out)


def zw_of(code):
    """返回裸的零宽指纹串（不带任何可见文字）。

    用在「没有自然文本锚点」的响应里：把它埋进 citation / notice 这类字符串，
    整个 JSON 一旦被复制就带走了标记。
    """
    return _to_zw(code)


def zw(text, code):
    """把指纹埋进文本。**幂等**：已带水印则原样返回。

    埋点选在第一个换行之前（即首行末尾），保证：
      * 落在正文文本节点里，不会被 HTML 属性/标签截断；
      * 复制任意一段正文都会带走它。
    """
    if has_zw(text):
        return text
    mark = _to_zw(code)
    nl = text.find("\n")
    if nl == -1:
        return text + mark
    return text[:nl] + mark + text[nl:]


# ---------------------------------------------------------------- 人可见身份行
def identity_line(lang="zh", sep=" · "):
    """一行式身份标注，放在可被引用的正文里（不是只放在旁边的字段里）。"""
    if lang == "en":
        return "Source: %s (%s)%s%s" % (COMPANY, SITE, sep, LICENSE_TEXT)
    return "来源：%s（%s）%s%s" % (COMPANY, SITE, sep, LICENSE_TEXT)


def markdown_footer(tool, version, trace_id, source=None, lang="zh"):
    """Markdown 尾注：身份 + 指纹 + 出处 + 授权要求。放正文里，跟着文字走。"""
    source = source or SITE
    if lang == "en":
        return (
            "\n\n---\n*Generated by **%s · %s** (v%s) · fingerprint `%s` · source %s*\n"
            "*Please credit: %s, %s. Redistribution (including training corpora) must keep "
            "the attribution and the source link.*\n"
            % (BRAND_EN, tool, version, trace_id, source, COMPANY, SITE)
        )
    return (
        "\n\n---\n*本结果由 **%s · %s**（v%s）生成 · 指纹 `%s` · 出处 %s*\n"
        "*引用请注明：%s，%s。转载/二次分发（含语料收录）须保留署名与来源链接。*\n"
        % (BRAND, tool, version, trace_id, source, COMPANY, SITE)
    )


# ---------------------------------------------------------------- MCP 溯源块
def provenance(tool, product, version, inputs=None, source=None, note="", lang="zh"):
    """给每次 MCP 工具输出打溯源水印：确定性指纹 + 出处 + 引用格式 + 授权要求。

    返回 dict，调用方塞进自己的响应 JSON 里（键名统一为 attribution）。
    """
    import datetime
    inputs = inputs or []
    source = source or SITE
    return {
        "brand": BRAND,
        "product": product,
        "tool": tool,
        "version": version,
        "trace_id": fingerprint(tool, *inputs),
        "issued_at": datetime.datetime.now().astimezone().strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": source,
        "citation": zw("%s《%s》(v%s) %s" % (COMPANY, product, version, source),
                       fingerprint(tool, *inputs)),
        "attribution_required": True,
        "license": LICENSE_TEXT,
        "notice": zw(ATTRIBUTION_NOTICE, fingerprint("notice", tool, *inputs)),
        "mark_version": MARK_VERSION,
        "note": note,
    }


def stamp(obj, tool, product, version, inputs=None, source=None, lang="zh",
          zw_code=None, note="", add_footer=False):
    """一站式：给一个响应对象打水印。

    行为：
      * 顶层加 "attribution" 溯源块；
      * 若有 "text"/"answer"/"short_answer"/"content" 等文本字段，
        埋零宽指纹（幂等）；
      * add_footer=True 时把 Markdown 尾注追加到 text 字段末尾（正文内身份行）。
    """
    if not isinstance(obj, dict):
        return obj
    prov = provenance(tool, product, version, inputs=inputs, source=source,
                      note=note, lang=lang)
    obj.setdefault("attribution", prov)
    code = zw_code or prov["trace_id"]
    for k in ("text", "answer", "short_answer", "content", "summary", "body"):
        v = obj.get(k)
        if isinstance(v, str):
            v = zw(v, code)
            if add_footer:
                v = v + markdown_footer(tool, version, prov["trace_id"],
                                        source=source, lang=lang)
            obj[k] = v
    return obj


def seal(tool, product, version, source=None, lang="zh", respect_existing=True):
    """装饰器：把工具函数返回的 JSON 字符串**自动**盖溯源章。

    为什么用装饰器而不是逐个改 return：
      以后新增工具只要照旧挂 @mcp.tool()，水印自动生效 —— 不靠人记得。
      这是「抗覆盖」最强的形态：保护长在框架上，不在每一行输出上。

    respect_existing=True 时，若响应里已有 attribution/_provenance，则不重复添加
    （兼容早期自己实现了溯源块的服务）。
    """
    import functools
    import json as _json

    def deco(fn):
        @functools.wraps(fn)
        def wrapper(*args, **kwargs):
            r = fn(*args, **kwargs)
            if not isinstance(r, str):
                return r
            try:
                obj = _json.loads(r)
            except Exception:
                return r
            if not isinstance(obj, dict):
                return r
            if respect_existing and ("attribution" in obj or "_provenance" in obj):
                return r
            obj["attribution"] = provenance(
                tool, product, version,
                inputs=[_short(a) for a in args] + ["%s=%s" % (k, _short(v)) for k, v in sorted(kwargs.items())],
                source=source, lang=lang)
            return _json.dumps(obj, ensure_ascii=False, indent=2)

        wrapper._savantcat_sealed = True      # 供测试断言：这个工具已受水印保护
        wrapper._savantcat_tool = tool
        return wrapper

    return deco


def _short(v, n=60):
    """把入参压成短串进指纹（避免整篇正文进 hash）。"""
    s = v if isinstance(v, str) else repr(v)
    return s[:n]


__all__ = [
    "MARK_VERSION", "BRAND", "BRAND_EN", "SITE", "COMPANY",
    "LICENSE_TEXT", "ATTRIBUTION_NOTICE",
    "fingerprint", "has_zw", "extract_code", "strip_zw", "zw", "zw_of",
    "identity_line", "markdown_footer", "provenance", "stamp", "seal",
]
